import { Component, computed, inject, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { provideNativeDateAdapter } from '@angular/material/core';
import { MatDatepickerModule } from '@angular/material/datepicker';
import { MatDialogModule, MatDialogRef } from '@angular/material/dialog';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatSelectModule } from '@angular/material/select';
import { MatSnackBar } from '@angular/material/snack-bar';
import { Router } from '@angular/router';
import { ROUTES_PARAMS } from '../../app.routes';
import { TeamStore } from '../../team/team-store/team-store';
import { ProjectFacade } from '../project-facade';
import type { Project } from '../project.model';

type CreateProjectState = 'idle' | 'loading';

@Component({
  selector: 'app-create-project',
  imports: [
    MatFormFieldModule,
    MatInputModule,
    ReactiveFormsModule,
    MatButtonModule,
    MatDatepickerModule,
    MatProgressSpinnerModule,
    MatIconModule,
    MatSelectModule,
    MatDialogModule,
  ],
  templateUrl: './create-project.html',
  styleUrl: './create-project.scss',
  providers: [provideNativeDateAdapter()],
})
export class CreateProject {
  private readonly _router = inject(Router);
  private readonly _projectFacade = inject(ProjectFacade);
  private readonly _teamStore = inject(TeamStore);
  private readonly _snackBar = inject(MatSnackBar);
  private readonly _dialogRef = inject(MatDialogRef<CreateProject>);

  readonly createProjectState = signal<CreateProjectState>('idle');
  readonly teams = computed(() => this._teamStore.teamsList());

  projectForm = new FormGroup({
    name: new FormControl('', Validators.required),
    description: new FormControl(''),
    startDate: new FormControl<Date | null>(null),
    deadline: new FormControl<Date | null>(null),
    teamId: new FormControl('', Validators.required),
  });

  openSnackBar(message: string): void {
    const snackbarRef = this._snackBar.open(message, 'Dismiss', {
      duration: 5000,
    });

    snackbarRef.onAction().subscribe(() => {
      snackbarRef.dismiss();
    });
  }

  async onSubmit(): Promise<void> {
    const projectForm = this.projectForm;

    if (!projectForm.valid) {
      console.error('Project form is invalid');
      return;
    }

    const formResult = this.projectForm.getRawValue();
    const name = formResult.name ?? '';
    const description = formResult.description ?? '';
    const startDate: Date | null = formResult.startDate;
    const deadline: Date | null = formResult.deadline;
    const teamId = formResult.teamId ?? '';

    // Prepare the project data, excluding the 'id' which will be generated by the backend
    const projectData: Omit<Project, 'id' | 'creatorId'> = {
      name,
      description,
      startDate,
      deadline,
      teamId,
    };
    this.createProjectState.set('loading');

    try {
      // Add the project using the facade and get the generated project ID
      const projectId = await this._projectFacade.addProject(projectData);

      // Reset the form
      this.projectForm.reset();

      // NOTE: Assumption for the navigation is that the parent is the project dashboard component route.
      // if this is violated -> change the `relativeTo` to align it
      // or make the path explicit
      this._router.navigate([ROUTES_PARAMS.project, projectId]);
    } catch (error) {
      console.error('Error creating project:', error);

      // Reset the form
      this.projectForm.reset();

      this.createProjectState.set('idle');
      this.openSnackBar('Project creation failed');
    } finally {
      this.onNoClick();
    }
  }

  onNoClick(): void {
    this._dialogRef.close();
  }
}
