import { Component, inject, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { provideNativeDateAdapter } from '@angular/material/core';
import { MatDatepickerModule } from '@angular/material/datepicker';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { ActivatedRoute, Router } from '@angular/router';
import { ProjectFacade } from '../../application/facades/project-facade';
import type { Project } from '../project.types';
@Component({
  selector: 'app-create-project',
  imports: [
    MatFormFieldModule,
    MatInputModule,
    ReactiveFormsModule,
    MatButtonModule,
    MatDatepickerModule,
    MatProgressSpinnerModule,
  ],
  templateUrl: './create-project.html',
  styleUrl: './create-project.scss',
  providers: [provideNativeDateAdapter()],
})
export class CreateProject {
  private router = inject(Router);
  private route = inject(ActivatedRoute);
  private projectFacade = inject(ProjectFacade);

  private navigateToProjectDashboard: (id: string) => Promise<boolean> = (id: string) =>
    this.router.navigate(['project-dashboard', id], { relativeTo: this.route });

  isLoading = signal<boolean>(false);

  projectForm = new FormGroup({
    projectName: new FormControl('', Validators.required),
    deadline: new FormControl('', Validators.required),
  });

  async onSubmit(): Promise<void> {
    if (this.projectForm.valid) {
      const formResult = this.projectForm.value;

      // Prepare the project data, excluding the 'id' which will be generated by the backend
      const projectData: Omit<Project, 'id'> = {
        name: formResult.projectName!,
        deadline: formResult.deadline!,
      };

      this.isLoading.set(true);

      try {
        // Add the project using the facade and get the generated project ID
        const projectId = await this.projectFacade.addProject(projectData);
        this.navigateToProjectDashboard(projectId);
      } catch (error) {
        console.error('Error creating project:', error);
      } finally {
        this.isLoading.set(false);
      }
    } else {
      console.log('Form is invalid');
    }
  }
}
